---
abstract: 'simple policy for enforcing a package naming policy'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Class: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-RequirePackageNamePattern
provides:
  Perl::Critic::Policy::logicLAB::RequirePackageNamePattern:
    file: lib/Perl/Critic/Policy/logicLAB/RequirePackageNamePattern.pm
    version: 0.02
requires:
  Carp: 0
  Data::Dumper: 0
  Perl::Critic: 0
  Perl::Critic::Policy: 0
  Perl::Critic::Utils: 0
  perl: v5.6.0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCPLRPNP#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCPLRPNP
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCPLRPNP/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-Policy-logicLAB-RequirePackageNamePattern
  homepage: http://logiclab.jira.com/wiki/display/PCPLRPNP/Home
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/jonasbn/pcplrpnp
version: 0.02
